# Generated by Django 3.1.2 on 2021-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='tags',
        ),
        migrations.AddField(
            model_name='faq',
            name='tags',
            field=models.CharField(default='tag', max_length=10),
            preserve_default=False,
        ),
    ]
