# Generated by Django 3.1.2 on 2021-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20210902_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='tags',
            field=models.CharField(max_length=60),
        ),
    ]
