# Generated by Django 3.1.2 on 2021-08-23 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210823_2320'),
    ]

    operations = [
    ]
