# Generated by Django 3.1.2 on 2021-08-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210824_1830'),
        ('account', '0016_auto_20210824_1732'),
    ]

    operations = [
    ]
