# Generated by Django 3.1.2 on 2021-09-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20210824_1917'),
        ('account', '0018_auto_20210902_1701'),
    ]

    operations = [
    ]
