# Generated by Django 2.2.19 on 2021-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupPlotNo', models.CharField(max_length=300)),
                ('pickupStreet', models.CharField(max_length=300)),
                ('pickupCity', models.CharField(max_length=300)),
                ('pickupState', models.CharField(max_length=300)),
                ('pickupPin', models.IntegerField(max_length=6)),
            ],
        ),
    ]
