# Generated by Django 2.2.19 on 2021-06-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickupPin',
            field=models.IntegerField(verbose_name=6),
        ),
    ]
