# Generated by Django 3.1.2 on 2021-06-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_auto_20210602_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickupPin',
            field=models.IntegerField(),
        ),
    ]
