# Generated by Django 3.1.2 on 2021-10-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_talktous'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestACallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cont', models.CharField(max_length=1000)),
            ],
        ),
    ]
