# Generated by Django 2.2.13 on 2021-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210802_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/image.jpg', upload_to='pics'),
        ),
    ]
