# Generated by Django 2.2.13 on 2021-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='theseventhsquare', max_length=60),
        ),
    ]
