# Generated by Django 3.1.7 on 2021-03-04 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(blank=True, max_length=200, null=True)),
                ('product_deatails', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to=inventory.models.get_file_path)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=100, null=True)),
                ('hsnCode', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantee', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(default=0)),
                ('marked', models.CharField(blank=True, max_length=100, null=True)),
                ('colour', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=10)),
                ('qty', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('basePrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sellPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('commercialPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
