# Generated by Django 3.0.8 on 2021-03-06 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210306_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='countryoforigin',
            new_name='countryOfOrigin',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Guarantee',
            new_name='guarantee',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='inventorystatus',
            new_name='inventoryStatus',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='sub_Category',
            new_name='subCategory',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='Warranty',
            new_name='warranty',
        ),
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
