# Generated by Django 3.1.2 on 2021-05-10 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210510_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='commercialPrice',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
