# Generated by Django 3.1.2 on 2021-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210510_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='colors',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
