# Generated by Django 3.1.2 on 2021-05-10 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210510_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='commercialPrice',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
