# Generated by Django 3.1.2 on 2021-05-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210510_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='dimensionUnit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
