# Generated by Django 3.1.2 on 2021-05-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventory_dimensionunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
