# Generated by Django 3.1.2 on 2021-07-06 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventory_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='qty',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
