# Generated by Django 3.1.2 on 2021-08-23 16:55

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20210822_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='image',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name=inventory.models.get_file_path)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
