# Generated by Django 3.1.2 on 2021-08-23 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210823_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sellingPrice',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
