# Generated by Django 3.1.2 on 2021-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210823_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='discount',
            field=models.IntegerField(default=10),
        ),
    ]
