# Generated by Django 3.1.2 on 2021-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_inventory_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
