# Generated by Django 3.1.2 on 2021-08-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20210824_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
