# Generated by Django 3.1.2 on 2021-09-26 15:53

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('inventory', '0025_auto_20210824_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='product_tags'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='aboutBrand',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='aboutHandling',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='aboutInstallation',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='aboutStorage',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='aboutUsage',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qtyUnit',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='variant',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
