# Generated by Django 3.1.2 on 2021-09-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20210926_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='brand_name',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='incl_gst',
            field=models.BooleanField(default=False),
        ),
    ]
