# Generated by Django 3.1.2 on 2021-09-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20210927_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='incl_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
